# Generated by Django 2.2.5 on 2019-09-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='c_pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Module'),
        ),
    ]
