# Generated by Django 2.2.5 on 2019-09-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20190920_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='c_pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Module'),
        ),
    ]
